projectName: Fr1_mut_RNAseq
dataDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/vorholt/akeppler/22AK06/scratch/fr1_rnaseq/data
outDir: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/vorholt/akeppler/22AK06/scratch/fr1_rnaseq
samples: /nfs/nas22/fs2202/biol_micro_bioinf_nccr/vorholt/akeppler/22AK06/scratch/fr1_rnaseq/configs/Fr1_mut_RNAseq_samples.csv

sanitise_name: false
name_delimiter: _
name_index: 3
fq_fwd: _1.fq.gz
fq_rvr: _2.fq.gz
se: false

#Preprocessing
qc: yes
mink: 11
trimq: 14 # 37
mapq: 20
minlen: 45

fastqc: no # Options: no, before, after, both
merge_replicates: false

# STAR/BWA
refGenome: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/ref/Fr1/Fr1_final.fasta
refAnn:
refGff: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/ref/Fr1/Fr1_prokka_conv_noFasta.gff
genomeDir:
overhang:
maxIntron:
genomeSAindexNbases:

# featureCounts
strand: 'no'
attribute: gene_id


# htseq-count
feature_type: gene



# salmon/kallisto

transcriptome: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/ref/GRCm39/Mus_musculus.GRCm39.cdna.all.fa.gz
kallistoIdx:




# Standard parameters. Dont change these!!!
adapters: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/adapters.fa'
phix: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/phix174_ill.ref.fa.gz'
bbmap_human_ref: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/human_bbmap_ref/'
bbmap_mouse_ref: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/mouse_bbmap_ref/'

# todo move these to resources

