projectName: TAIR10_basic
dataDir: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/test_data/rnaseq/tair10/raw
outDir: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/test_data/test_out/tair10
samples: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/ansintsova/test_data/test_out/tair10/TAIR10_basic_sample.csv

sanitise_name: true
name_delimiter: _
name_index: 1
fq_fwd: _1.fq.gz
fq_rvr: _2.fq.gz
se: false

#Preprocessing
qc: yes
mink: 11
trimq: 14 # 37
mapq: 20
minlen: 45

fastqc: no # Options: no, before, after, both
merge_replicates: false

# STAR
refGenome: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/ref/TAIR10/Arabidopsis_thaliana.TAIR10.dna_sm.toplevel.fa.gz
refAnn: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/ref/TAIR10/Arabidopsis_thaliana.TAIR10.51.gtf
refGff: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/ref/TAIR10/Arabidopsis_thaliana.TAIR10.51.gff3
genomeDir: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/ref/TAIR10/star_index
overhang: 149
maxIntron: 50000
genomeSAindexNbases: 12


# featureCounts
strand: 0
attribute: gene_id

# salmon/kallisto

transcriptome: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/ref/TAIR10/Arabidopsis_thaliana.TAIR10.cdna.all.fa.gz
kallistoIdx: /nfs/cds-peta/exports/biol_micro_cds_gr_sunagawa/scratch/Projects_NCCR/ref/ath/AtRTD2_19April2016.idx




# Standard parameters. Dont change these!!!
adapters: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/adapters.fa'
phix: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/phix174_ill.ref.fa.gz'
bbmap_human_ref: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/human_bbmap_ref/'
bbmap_mouse_ref: '/nfs/cds-shini.ethz.ch/exports/biol_micro_cds_gr_sunagawa/SequenceStorage/resources/mouse_bbmap_ref/'

# todo move these to resources

